config/routes.rb
Rails.application.routes.draw do
root 'images#index'

resources :users, only: [:index, :new, :create, :show]

resource :session, only: [:new, :create, :destroy]

resources :images, only: [:index, :new, :show, :create, :destroy, :update, :edit]

resources :profiles, only: [:index]

resources :upvotes, only: [:update]

get '/upvote/:id', to: 'images#upvote'

get '/login', to: 'session#new'

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :upvote_instances, class_name: "Upvote", dependent: :destroy
  belongs_to :uploader, class_name: "User"
  has_many :upvoted_by, class_name: "User", through: :upvotes

  def upvotes
    upvote_instances.length
  end

  has_attached_file :link, styles: { index: "250x350>", show: "325x475>" }
  validates_attachment_content_type :link, content_type: /\Aimage\/.*\Z/
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :uploads, class_name: "Image"
  has_many :upvoted, class_name: "Image", through: :upvotes


   has_secure_password
   has_many :images
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  helper_method :current_user

  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: "Not authorized, log in first" if current_user.nil?
   end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def show

  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    @image.update(image_params)
    redirect_to root_path
  end

  def create
    @image = Image.new(image_params)
    @image.user = current_user
    if @image.save
      flash[:notice] = "you posted a image good for you "
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @image = current_user.images.find(params[:id])
    @image.destroy
    redirect_to user_path(current_user)
  end


  def image_params
    params.require(:image).permit(:description, :link)
  end




end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new

end

def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(current_user), notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login - try again!'
      render 'new'
    end
end

def destroy
   session[:user_id] = nil
  redirect_to root_path, notice: "Logged out!"

end

end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController

  def update
    upvote = Upvote.new
    upvote.user = current_user
    image = Image.find(params[:id])
    upvote.image = image
    upvote.save
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate, only: [:show, :edit, :update]
before_action :authorize, only: [:show, :edit, :update]

def index
  @users = User.all
end

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You have successfully signed up!"
      session[:user_id] = @user.id # login
      redirect_to user_path(@user)
    else
      render :new
    end
end

def show

end

private

   def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def authenticate
    redirect_to new_session_path, alert: 'You must be logged in to continue!' if current_user.nil?
  end

  def authorize
    @user = User.find(params[:id])
    redirect_to root_path if @user != current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
  <header>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <%= link_to "Cats of Disney", root_path %>
      &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
      <% if current_user %>
        <%= link_to "#{current_user.name}", user_path(current_user) %>
      <% else %>
        <%= link_to "Sign Up", new_user_path %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to "Sign In", new_session_path %>
      <% end %>
    </nav>
  </header>



<%= form_for @image do |f| %>
  <% if @image.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
<!--   <div class="field" id="firstblock">
    <%= f.label :link %>

  </div> -->
  <div class="field" id="firstblock">
    <%= f.file_field :link %>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="actions"><%= f.submit %></div>
 </div>
<% end %>

app/views/images/edit.html.erb
  <header>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <%= link_to "Cats of Disney", root_path %>
      &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
      <% if current_user %>
        <%= link_to "#{current_user.name}", user_path(current_user) %>
      <% else %>
        <%= link_to "Sign Up", new_user_path %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to "Sign In", new_session_path %>
      <% end %>
    </nav>
  </header>



<%= form_for @image do |f| %>
  <% if @image.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
 </div>
  <div class="field" id="firstblock">
    <%= f.file_field :link %>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="actions"><%= f.submit %></div>
 </div>
<% end %>

app/views/images/index.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">

    <% if current_user %>
      <%= link_to "#{current_user.name.capitalize}", user_path(current_user) %>
      &nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
      <%= link_to "", new_image_path, :class => "glyphicon glyphicon-camera" %>
      &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
      <%= link_to "Cat History", users_path %>
    <% else %>
       <%= link_to "Cats of Disney", root_path %>
      &nbsp;&nbsp;|&nbsp;&nbsp;
      <%= link_to "Sign Up", new_user_path %>
      &nbsp;&nbsp;|&nbsp;&nbsp;
      <%= link_to "Sign In", new_session_path %>
    <% end %>
  </nav>
</header>


  <div class="container" id="welcome">
    <% if current_user %>
      <% @images.reverse.each do |image| %>
      <div class="panel panel-default space center-block">
        <p class="posterName"><%= image.user.name.capitalize %></p>
        <p><%= image_tag image.link.url(:index) %></p>
        <p class="imageDesc"><%= image.description %></p>

          <% if image.upvote_instances.where(user_id:current_user).length > 0 %>
            <link disabled class="glyphicon glyphicon-heart"></link>
            &nbsp;&nbsp;|&nbsp;&nbsp;
          <% else %>
            <%= link_to "", upvote_path(image), method: :put, :class => "glyphicon glyphicon-heart-empty" %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
          <% end %>

        <%= image.upvotes %>
      </div>
      <% end %>
  </div>
    <% else %>
      <div class="disneyimage">
      <style>
        body {
          background: url("https://i.imgur.com/aHrVj7o.png");
          -webkit-background-size: cover;
          -moz-background-size: cover;
          -o-background-size: cover;
          background-size: cover;
          background-repeat: no-repeat;
        }


      </style>
      </div>
    <% end %>

app/views/images/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatsOfDisney</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="container-fluid">

  <div class="row" id="welcome">
      <div>
 <!--        <h2>When the Mice are away, the Cats can play.</h2> -->
<!--         <%=image_tag("crookandwalt.jpg")%> -->
      </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/index.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <%= link_to "Cats of Disney", root_path %>
    &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
      <%= link_to "#{current_user.name.capitalize}", user_path(current_user) %>
      &nbsp;&nbsp;&nbsp;
  </nav>
</header>

<body>
<div class="history">
 <div>From a Cat’s Point of View</div>

The Disneyland Cats have been around for as long as any of us can remember.
Our ancestors lived in Sleeping Beauty Castle before we were unceremoniously evicted.
Ever since then, we’ve prowled the streets and walkways of Disneyland (and more recently Disney California Adventure).
When it comes right down to it, we run the place. Without us, rodents would run amuck and the entire population of Disneyland
would be a lot less cute. We put up with the humans visiting our quarters, but only because they leave at night. There are
magical food stations positioned for us all around the property, and we get to eat whenever we like. Nowhere is off limits to us.
Disneyland is OUR land. And we try our best to forget it was “all started by a mouse.”

<div>
 &nbsp;&nbsp;&nbsp;
  <div>From a Human’s Point of View</div>

(* Note: Remember to take everything humans say with a grain of salt. They’re not the brightest.)

It’s impossible to pinpoint exactly when the first cats started to appear on Disneyland property, but there have been sightings going as far back as 1955. Soon after Disneyland opened, Walt decided that there should be an attraction inside of the park’s most prominent “weenie,” Sleeping Beauty Castle. When he brought imagineers into the castle to begin the planning process for what would eventually become the Castle Walkthrough attraction, he was greeted by quite the sight—scores of feral cats had set up a home for themselves inside the building. Not only that, but the cats had brought with them an infestation of fleas. It became clear that something needed to be done about the cats, but the Disney company knew they couldn’t exactly “eliminate” the problem without considerable uproar from guests. The immediate solution was to adopt out all the cats to cast members, ensure them good homes, and so free up some valuable real estate.
They dealt with the flea problem as quickly as possible too.
Meanwhile, being an outdoor theme park with lands meant to simulate rustic situations, Disneyland had developed a bit of a rodent problem. While the irony was lost on no one in the company, Disneyland had mice running around—and we’re not talking about Mickey and Minnie. There were also still plenty of feral cats on property who hadn’t set up shop in the castle. The cats were smart and realized they’d found a decent hunting ground on a property that was free of all the typical dangers stray cats have to face. They were able to emerge at night to a relatively empty park, and they could hunt in peace.

It was around this time that someone in the Disney company must have had a pretty brilliant idea. The cats weren’t bothering anyone—feral cats, by nature, are scared of humans—and they were doing a much better job with pest control than any human exterminators were likely to do. So the cats were put to work. More accurately, they were allowed to continue doing the work they were already doing, but now it was with Disney’s blessing, and some payment.
</div>




</div>


</body>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <%= link_to "Cats of Disney", root_path %>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <% if current_user %>
       <%= link_to "", new_image_path, :class => "glyphicon glyphicon-camera" %>
     &nbsp;&nbsp;|&nbsp;&nbsp;
     <%= link_to 'Log out', session_path('dummy'), method: :delete %>
     <% else %>
      <%= link_to "Sign Up", new_user_path %>
      &nbsp;&nbsp;|&nbsp;&nbsp;
      <%= link_to "Sign In", new_session_path %>
    <% end %>
  </nav>
</header>



<div class="container" id="welcome">
      <% current_user.images.reverse.each do |image| %>
      <div class="panel panel-default space center-block">
        <p class="posterName"><%= image.user.name.capitalize %></p>
        <p><%= image_tag image.link.url(:index) %></p>
        <p class="imageDesc"><%= image.description %></p>

        <% if image.upvote_instances.where(user_id:current_user).length > 0 %>
          <link disabled class="glyphicon glyphicon-heart"></link>
          &nbsp;&nbsp;|&nbsp;&nbsp;
           <%= image.upvotes %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
           <%= link_to "", image_path(image), :method => :delete, data:
            {:confirm => "Are You Sure You Want to Delete Your Post?"}, :class => "glyphicon glyphicon-trash" %>
        <% else %>
          <%= link_to "", upvote_path(image), method: :put, :class => "glyphicon glyphicon-heart-empty" %>
           &nbsp;&nbsp;|&nbsp;&nbsp;
           <%= image.upvotes %>
           &nbsp;&nbsp;|&nbsp;&nbsp;
           <%= link_to "", image_path(image), :method => :delete, data:
            {:confirm => "Are You Sure You Want to Delete Your Post?"}, :class => "glyphicon glyphicon-trash" %>

      </div>
        <% end %>
         &nbsp;&nbsp;|&nbsp;&nbsp;
      <%= link_to "Edit", edit_image_path(image.id) %>
</div>
      <% end %>